variables:
  buildConfiguration: 'Release'
pool:
    vmImage: 'macOS-10.14'
steps:

- script: npm install

- script: ng build

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'angular'
    targetPath: 'src/angular-devops/dist'